### ISSUE TITLE
Error reported after running:node:internal/process/promises:289             triggerUncaughtException(err, true /* fromPromise */);

### ISSUE THREAD

**Issue by shanlanCoding** [vogler/free-games-claimer#189] opened 2023-08-22 00:55 UTC
```shell
[root@localhost fgc]# docker run --rm -p 6080:6080 -v fgc:/fgc/data  --env-file=/fgc/config.env --privileged ec6dd9a5995d node epic-games
Xvfb display server created screen with resolution 1280x1280
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080

2023-08-21 12:27:13.251 started checking epic-games
Signed in as ***********
Free games: [
  'https://store.epicgames.com/en-US/p/black-book',
  'https://store.epicgames.com/en-US/p/dodo-peak-159276'
]
  This game contains mature content recommended only for ages 18+
Current free game: Black Book
  Already in library! Nothing to claim.
Current free game: Dodo Peak
  Already in library! Nothing to claim.
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ProtocolError: Target closed
    at /fgc/node_modules/playwright-core/lib/server/firefox/ffConnection.js:189:16
    at new Promise (<anonymous>)
    at FFSession.send (/fgc/node_modules/playwright-core/lib/server/firefox/ffConnection.js:185:12)
    at RawMouseImpl.move (/fgc/node_modules/playwright-core/lib/server/firefox/ffInput.js:91:24)
    at Mouse.move (/fgc/node_modules/playwright-core/lib/server/input.js:153:23)
    at Mouse.click (/fgc/node_modules/playwright-core/lib/server/input.js:180:12)
    at /fgc/node_modules/playwright-core/lib/server/dom.js:468:109
    at /fgc/node_modules/playwright-core/lib/server/dom.js:430:13
    at FrameManager.waitForSignalsCreatedBy (/fgc/node_modules/playwright-core/lib/server/frames.js:114:26)
    at ElementHandle._performPointerAction (/fgc/node_modules/playwright-core/lib/server/dom.js:424:57) {
  sessionClosed: true
}

Node.js v19.9.0

```
I ran it through EpicAuto, and the sh content is shown in the following figure:
![image](https://github.com/vogler/free-games-claimer/assets/44717382/f159bb4e-f7ef-4227-b33a-a825ea2dde10)
The screenshot of the error message is as follows:
![image](https://github.com/vogler/free-games-claimer/assets/44717382/26dc1612-abbb-452f-90dc-90b394bd6ad1)

**Comment by vogler** [comment] 2023-12-23 20:43
Duplicate of #170.
Why are you using some id to run it instead of the command from the Readme? This won't update.

**Closed by vogler** 2023-12-23 20:43 UTC
Labels: can't reproduce

**Comment by arnoldknott** [comment] 2024-01-11 21:43
Did you forget an `await` in your code?

**Comment by threeng0227** [comment] 2024-07-12 08:08
Node 20 and RN 0.73 not working
