### ISSUE TITLE
Stuck in hCaptcha "failed to challenge captcha, please try again later" loop with epic-games.js

### ISSUE THREAD

**Issue by nett00n** [vogler/free-games-claimer#254] opened 2023-11-17 10:50 UTC
I have a docker-compose installation on my x86_64 machine:

```docker-compose.yml
---
version: '3.7'
services:
  nett00n:
    networks:
      - default
    image: ghcr.io/vogler/free-games-claimer:latest
    restart: always
    volumes:
      - ./data:/fgc/data
    ports:
      - 6081:6080
    command: bash -c 'node epic-games; node gog; sleep 12h'
    env_file:
      - nett00n.env
    labels:
      com.centurylinklabs.watchtower.enable: "true"
```

It was showing me hcaptcha for the last couple of weeks but i was solving it manually with no problem.

Yesterday i started to receive this error message after solving captcha no mater what:

![image](https://github.com/vogler/free-games-claimer/assets/1846116/ccbd51c2-69af-4eee-aa32-8d944416b1a0)

i've already tried:
- changing the resolution of the virtual screen
- changing useragent in /fgc/epic-games.js
- deleting data/browser/nett00n/storage/default/https+++store.epicgames.com/cache
- deleting data/browser/nett00n/cache2
- starting new data directory (cannot solve hcaptcha for login process)

![image](https://github.com/vogler/free-games-claimer/assets/1846116/e05c2963-c16c-42d7-8fae-bf89c1a7e855)

**Comment by sero2kk** [comment] 2023-11-18 13:19
i have the same problem with the captcha

**Comment by Prototype7813** [comment] 2023-11-18 23:43
Hi ! 

I have also the same issue . 

Thank you for your help

**Comment by ezek1el** [comment] 2023-11-19 08:31
Same problem here.

**Comment by alexmi256** [comment] 2023-11-19 15:13
Seeing the same issue

**Comment by necromancyr** [comment] 2023-11-20 18:11
Commented on this in #183 a week or so ago, just to link the two issues together as it could be related (and escalation) of the captcha showing.

**Comment by Albirew** [comment] 2023-11-22 21:55
same here:
![Screenshot 2023-11-22 at 22-37-03 noVNC](https://github.com/vogler/free-games-claimer/assets/2805161/33ec7b68-89ae-4c93-97b0-687b5069a1fe)
may be related to epic's headless browser detection since i don't get these captchas on my browser...
maybe trying to make browser a little more unique by adding some random JS-derived characteristics like browser language, timezone and time offset, system fonts, etc., anyway, anything you can see in panopticlick's detailed results...

**Comment by iAmP1us** [comment] 2023-11-24 10:14
same as you, i have tried many times but failed due to captcha

**Comment by vogler** [comment] 2023-11-24 10:29
So you were able to manually solve the captcha via VNC and now you can't anymore?
Yea, related to #183. Will have to try changing/upgrading different parts of the docker image to see what helps.
You can try with an updated Ubuntu and/or a different window manager, VNC server etc.

**Comment by JunkiEDM** [comment] 2023-11-30 16:23
> So you were able to manually solve the captcha via VNC and now you can't anymore? Yea, related to #183. Only workaround is to run without docker for now. Will have to try changing/upgrading different parts of the docker image to see what helps. You can try with an updated Ubuntu and/or a different window manager, VNC server etc.

I run without docker and I'm getting the same thing now even after manually completing captchas successfully (Windows 11)
![image](https://github.com/vogler/free-games-claimer/assets/8350274/44ec0225-8f1f-4a9c-9be2-67103b499b66)

https://github.com/vogler/free-games-claimer/assets/8350274/0262825f-656b-4122-9fd3-84688e717601

PS: i have no idea what this "head of the animal" captcha is supposed to be and i'm convinced its just an impossible timewaste

**Comment by iAmP1us** [comment] 2023-12-01 02:42
same as your post img，i also completed captcha successfully, but failed.发自我的 iPad在 2023年12月1日，00:23，Juan ***@***.***> 写道：﻿

So you were able to manually solve the captcha via VNC and now you can't anymore? Yea, related to #183. Only workaround is to run without docker for now. Will have to try changing/upgrading different parts of the docker image to see what helps. You can try with an updated Ubuntu and/or a different window manager, VNC server etc.

I run without docker and I'm getting the same thing now even after manually completing captchas successfully (Windows 11)
image.png (view on web)
https://github.com/vogler/free-games-claimer/assets/8350274/0262825f-656b-4122-9fd3-84688e717601
PS: i have no idea what this "head of the animal" captcha is supposed to be and i'm convinced its just an impossible timewaste

**Comment by vogler** [comment] 2023-12-18 21:26
Sorry, busy with work, I can try to fiddle around with the docker image over the holidays.

@JunkiEDM @iAmP1us So you both also get a catpcha without docker under Windows 11? Seems strange since there are probably more people running it on Windows. I get not captchas on macOS.

**Comment by Hamza141** [comment] 2023-12-18 21:59
@vogler just to add another data point, I'm running this on unraid and getting captchas

**Comment by vogler** [comment] 2023-12-18 22:04
Yea, that's a problem with the docker image, see #183.

**Comment by Mrgaton** [comment] 2023-12-20 18:55
![image](https://github.com/vogler/free-games-claimer/assets/68958481/5434c754-5042-4232-93dc-829e29bbec54)
Same issue

**Comment by Tylerjet** [comment] 2023-12-21 05:01
Just as another +1, I am running this on a Proxmox LXC (Ubuntu 22.04) not in docker and running into the same above captcha issues.

**Comment by vogler** [comment] 2023-12-21 09:00
Yea, seems like it's even a problem on stock Ubuntu Desktop in a VM as noted in https://github.com/vogler/free-games-claimer/issues/183#issuecomment-1863498431.
So likely no fonts etc. but something about Playwright on Ubuntu and/or virtualization (not sure how that should be visible to the browser though).

**Comment by vogler** [comment] 2023-12-21 09:24
@JunkiEDM @iAmP1us Are you getting captchas on non-virtualized Windows? If not, we can close this as duplicate of #183.

**Comment by Mrgaton** [comment] 2023-12-21 10:57
> @JunkiEDM @iAmP1us Are you getting captchas on non-virtualized Windows? If not, we can close this as duplicate of #183.

I can't login due to captcha on my real windows too

**Comment by vogler** [comment] 2023-12-23 20:18
Yea, the problem seems to be with running the script on Linux in general, see https://github.com/vogler/free-games-claimer/issues/183#issuecomment-1866988403

**Closed by vogler** 2023-12-23 20:18 UTC
Labels: docker, captcha
