### ISSUE TITLE
Raspberry Pi keeps getting Captcha prompt'd

### ISSUE THREAD

**Issue by SapitoSucio** [vogler/free-games-claimer#265] opened 2023-12-06 15:19 UTC
I installed this amazing claimer on my Pi4 

I set up a .sh script to run two commands; the `docker run --rm -p 6080:6080 -v fgc:/fgc/data --pull=always -e BROWSER_DIR=data/xxxxxx` for each account

Epic Games fails at claiming because it always gets Captcha.

interestingly enough, when I try to manually claim it on my PC, i don't get any captcha, so it's not a IP flag thing

**Comment by bi0shacker001** [comment] 2023-12-14 14:36
Duplicate of #182 #183 #254 #260 #261 
Please search before submitting issues

**Closed** 2023-12-18 20:55 UTC
