### ISSUE TITLE
Timeout claiming Prime games

### ISSUE THREAD

**Issue by Kraker01** [vogler/free-games-claimer#62] opened 2023-02-16 08:35 UTC
Hi, 
i've done a fresh install of NodeJs (19.6.0 and npm 9.5.0) on a Windows 10 machine. I've no problem using GOG and EPic Games claimer (i'm using the latest version available updated 13hours ago). This is the error i'm getting:

```
Catch error: page.click: Timeout 20000ms exceeded.
=========================== logs ===========================
waiting for locator('button[data-type="Game"]')
============================================================
    at file:///C:/Users/ 'xxx' /Downloads/free-games-claimer-main/prime-gaming.js:85:14 {
  name: 'TimeoutError'
}
```

**Comment by vogler** [comment] 2023-02-16 15:28
Can't reproduce. The text of the button changed to `Weekly games`, but `data-type="Game"` is still the same.
Can you check with `SHOW=1` what's happening?

**Comment by gitrep3** [comment] 2023-02-21 19:51
I have the same issue, unfortunately is also exits with code 0 so my script thinks everything worked fine.

**Comment by vogler** [comment] 2023-02-21 20:07
Exit code fixed in 704c4b01e1efb3c08b9cc81891211e5c802708bd.
Do you have some details? For me the locator finds the button.

**Comment by gitrep3** [comment] 2023-02-21 20:13
Thank you! I will try to reproduce it when I am back at my laptop

**Comment by gitrep3** [comment] 2023-02-21 21:03
Okay I gave it a try and it consistently presented me the timeout:

```
games-claimer-epic-1  | Xvfb display server created screen with resolution 1280x1280
games-claimer-epic-1  | VNC is running on port 5900 (no password!)
games-claimer-epic-1  | noVNC (VNC via browser) is running on http://localhost:6080
games-claimer-epic-1  | 
games-claimer-epic-1  | 2023-02-21 20:50:12.223 started checking epic-games
games-claimer-epic-1  | Signed in as gitrep3
games-claimer-epic-1  | locator.waitFor: Timeout 20000ms exceeded.
games-claimer-epic-1  | =========================== logs ===========================
games-claimer-epic-1  | waiting for locator('a:has(span:text-is("Free Now"))').last() to be visible
games-claimer-epic-1  | ============================================================
games-claimer-epic-1  |     at file:///fgc/epic-games.js:96:25 {
games-claimer-epic-1  |   name: 'TimeoutError'
games-claimer-epic-1  | }
games-claimer-epic-1 exited with code 1
```

_Exit code triggered my own notification system so that works flawlessly now 🥳_ 

I tried connecting to noVNC to see what is happening but everything was waaaay to slow, when my browser finally loaded the VNC it already exited, so I increased the environment `TIMEOUT=60` and this seems to fix the issue for me.
I triggered it several times now and didn't get the error anymore.

Container is running on a very [low performance hardware](https://www.fujitsu.com/at/products/computing/pc/thin-clients/futro-s740/), I think its either that or my shitty internet connection.

Thanks for your quick response and this project in general!

**Comment by vogler** [comment] 2023-02-21 23:01
The low `TIMEOUT` of 20s was mainly for development and due to the fact that it was high enough for the machines I tried.
I can increase the default value to something more suitable for these kind of machines. Do you have a tighter bound than 60s? Otherwise I'll just set it to that.
Aside: I use a free Oracle VPS and it's pretty fast - in case you haven't seen: https://www.mydealz.de/deals/kostenloser-arm-server-mit-4-cpus-24gb-of-ram-and-200gb-storage-2096200

@Kraker01 can you confirm `TIMEOUT=60` working for you as well?

**Comment by gitrep3** [comment] 2023-02-21 23:20
20s gave me flaky results for both Epic and Gog (not using prime at all), it was a little worse for Epic, I guess because they use more JS on their site.

if 20s had a 50% chance to succeed, maybe 30s would have been enough but i don’t really see the appeal for it. On my productive automation I increased if even higher to 120s because I don’t care how long it takes as long as it is not completely stuck.

**Comment by gitrep3** [comment] 2023-02-23 17:14
And today it reliably claimed the free game for this week, very cool!

**Comment by Kraker01** [comment] 2023-02-24 15:21
Timeout partially solved the problem, now i got this:

Current free game: Duskers
  Not in library yet! Click GET.
page.click: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator('[data-testid="purchase-cta-button"]')
  locator resolved to <button class="css-1ppwb5u" data-testid="purchase-cta-bu…>…</button>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
============================================================
    at file:///C:/Users/***/Downloads/free-games-claimer/epic-games.js:136:18 {
  name: 'TimeoutError'
  
  I'm using the latest version download (the one updated 16hrs ago)

**Comment by vogler** [comment] 2023-02-24 17:36
@Kraker01 Yes, I got the same, see https://github.com/vogler/free-games-claimer/issues/62.
So, I can close this since prime-gaming works now for you with the increased timeout? What hardware are you running it on?

**Closed** 2023-02-24 20:07 UTC
Labels: store: prime-gaming, can't reproduce
