### ISSUE TITLE
epic-games `page.goto` timeout

### ISSUE THREAD

**Issue by someash** [vogler/free-games-claimer#135] opened 2023-05-08 12:43 UTC
three are three free games to chaim this week, but only two are claimed
![image](https://user-images.githubusercontent.com/32922655/236826930-a8b0ea62-aba0-41f0-924f-28ab24cf1858.png)
I have restart the docker several times but it is useless
![image](https://user-images.githubusercontent.com/32922655/236826750-ae0fe033-cd11-45a8-a72f-5fd32df27660.png)

**Comment by vogler** [comment] 2023-05-08 15:24
Can't reproduce. What does the log say? Is the first game not available in your region?

**Comment by someash** [comment] 2023-05-08 15:29
> Can't reproduce. What does the log say? Is the first game not available in your region?

No, this game is available in my region.
Maybe, you can tell me where is the log?
When i open the port 6080 to see, i find that the brower first turn to the second and third game, and finially turned to the first game page and do nothing at that page.

**Comment by vogler** [comment] 2023-05-08 15:34
The log is written to stdout, e.g. your Terminal. How do you run it?

> that the brower first turn to the second and third game, and finially turned to the first game

That's the order on https://store.epicgames.com/en-US/free-games:
![image](https://user-images.githubusercontent.com/493741/236866142-5ec913f6-1398-426d-8086-fde106dd1cec.png)

**Comment by someash** [comment] 2023-05-08 15:42
{"log":"Xvfb display server created screen with resolution 1280x1280\r\n","stream":"stdout","time":"2023-05-08T12:00:52.910496161Z"}
{"log":"VNC is running on port 5900 (no password!)\r\n","stream":"stdout","time":"2023-05-08T12:00:53.008755581Z"}
{"log":"noVNC (VNC via browser) is running on http://localhost:6080\r\n","stream":"stdout","time":"2023-05-08T12:00:53.008987587Z"}
{"log":"\r\n","stream":"stdout","time":"2023-05-08T12:00:53.009016259Z"}
{"log":"2023-05-08 12:00:53.348 started checking epic-games\r\n","stream":"stdout","time":"2023-05-08T12:00:53.350362824Z"}
{"log":"Not signed in anymore. Please login in the browser or here in the terminal.\r\n","stream":"stdout","time":"2023-05-08T12:01:07.71803181Z"}
{"log":"Open http://localhost:6080 to login inside the docker container.\r\n","stream":"stdout","time":"2023-05-08T12:01:07.718095379Z"}
{"log":"Login timeout is 180 seconds!\r\n","stream":"stdout","time":"2023-05-08T12:01:07.718641937Z"}
{"log":"Press ESC to skip the prompts if you want to login in the browser (not possible in headless mode).\r\n","stream":"stdout","time":"2023-05-08T12:01:11.473372421Z"}
{"log":"\u001b[?25l\u001b[36m?\u001b[39m \u001b[1mEnter email\u001b[22m \u001b[2m‣\u001b[22m \u001b[46m\u001b[30m\u001b[30m \u001b[39m\u001b[30m\u001b[39m\u001b[49m\u001b[1D\u001b[2K\u001b[1G\u001b[35m✖\u001b[39m \u001b[1mEnter email\u001b[22m \u001b[2m·\u001b[22m  timeout\u001b[8DWaiting for you to login in the browser.\r\n","stream":"stdout","time":"2023-05-08T12:04:11.490964091Z"}
{"log":"Signed in as Someash-Energy\r\n","stream":"stdout","time":"2023-05-08T12:04:11.608781635Z"}
{"log":"Free games: [\r\n","stream":"stdout","time":"2023-05-08T12:04:11.719949835Z"}
{"log":"  \u001b[32m'https://store.epicgames.com/en-US/p/against-all-odds-409105'\u001b[39m,\r\n","stream":"stdout","time":"2023-05-08T12:04:11.719994445Z"}
{"log":"  \u001b[32m'https://store.epicgames.com/en-US/p/horizon-chase-turbo'\u001b[39m,\r\n","stream":"stdout","time":"2023-05-08T12:04:11.719999926Z"}
{"log":"  \u001b[32m'https://store.epicgames.com/en-US/p/kao-the-kangaroo-62abe3'\u001b[39m\r\n","stream":"stdout","time":"2023-05-08T12:04:11.720004901Z"}
{"log":"]\r\n","stream":"stdout","time":"2023-05-08T12:04:11.720009257Z"}
{"log":"page.goto: Timeout 60000ms exceeded.\r\n","stream":"stdout","time":"2023-05-08T12:05:11.722587251Z"}
{"log":"=========================== logs ===========================\r\n","stream":"stdout","time":"2023-05-08T12:05:11.722634192Z"}
{"log":"navigating to \"https://store.epicgames.com/en-US/p/against-all-odds-409105\", waiting until \"load\"\r\n","stream":"stdout","time":"2023-05-08T12:05:11.722642998Z"}
{"log":"============================================================\r\n","stream":"stdout","time":"2023-05-08T12:05:11.722650788Z"}
{"log":"    at \u001b[90mfile:///fgc/\u001b[39mepic-games.js:114:16 {\r\n","stream":"stdout","time":"2023-05-08T12:05:11.722657778Z"}
{"log":"  name: \u001b[32m'TimeoutError'\u001b[39m\r\n","stream":"stdout","time":"2023-05-08T12:05:11.722665711Z"}
{"log":"}\r\n","stream":"stdout","time":"2023-05-08T12:05:11.722672579Z"}
{"log":"\u001b[?25h","stream":"stdout","time":"2023-05-08T12:05:12.098082633Z"}
{"log":"Xvfb display server created screen with resolution 1280x1280\r\n","stream":"stdout","time":"2023-05-08T12:11:16.405974169Z"}
{"log":"VNC is running on port 5900 (no password!)\r\n","stream":"stdout","time":"2023-05-08T12:11:16.499297701Z"}
{"log":"noVNC (VNC via browser) is running on http://localhost:6080\r\n","stream":"stdout","time":"2023-05-08T12:11:16.499511479Z"}
{"log":"\r\n","stream":"stdout","time":"2023-05-08T12:11:16.499539001Z"}
{"log":"2023-05-08 12:11:16.854 started checking epic-games\r\n","stream":"stdout","time":"2023-05-08T12:11:16.855805321Z"}
{"log":"Signed in as Someash-Energy\r\n","stream":"stdout","time":"2023-05-08T12:11:20.958185782Z"}
{"log":"Free games: [\r\n","stream":"stdout","time":"2023-05-08T12:11:24.858789858Z"}
{"log":"  \u001b[32m'https://store.epicgames.com/en-US/p/against-all-odds-409105'\u001b[39m,\r\n","stream":"stdout","time":"2023-05-08T12:11:24.858826615Z"}
{"log":"  \u001b[32m'https://store.epicgames.com/en-US/p/horizon-chase-turbo'\u001b[39m,\r\n","stream":"stdout","time":"2023-05-08T12:11:24.858844044Z"}
{"log":"  \u001b[32m'https://store.epicgames.com/en-US/p/kao-the-kangaroo-62abe3'\u001b[39m\r\n","stream":"stdout","time":"2023-05-08T12:11:24.858848662Z"}
{"log":"]\r\n","stream":"stdout","time":"2023-05-08T12:11:24.858853232Z"}
{"log":"Current free game: Against All Odds\r\n","stream":"stdout","time":"2023-05-08T12:11:42.210322505Z"}
{"log":"  Not in library yet! Click GET.\r\n","stream":"stdout","time":"2023-05-08T12:11:42.210425654Z"}
{"log":"  Claimed successfully!\r\n","stream":"stdout","time":"2023-05-08T12:12:06.637884274Z"}
{"log":"Current free game: Horizon Chase Turbo\r\n","stream":"stdout","time":"2023-05-08T12:12:24.317315057Z"}
{"log":"  Not in library yet! Click GET.\r\n","stream":"stdout","time":"2023-05-08T12:12:24.31739293Z"}
{"log":"  Claimed successfully!\r\n","stream":"stdout","time":"2023-05-08T12:12:41.139021732Z"}
{"log":"page.goto: Timeout 60000ms exceeded.\r\n","stream":"stdout","time":"2023-05-08T12:13:41.312835157Z"}
{"log":"=========================== logs ===========================\r\n","stream":"stdout","time":"2023-05-08T12:13:41.312897502Z"}
{"log":"navigating to \"https://store.epicgames.com/en-US/p/kao-the-kangaroo-62abe3\", waiting until \"load\"\r\n","stream":"stdout","time":"2023-05-08T12:13:41.312908765Z"}
{"log":"============================================================\r\n","stream":"stdout","time":"2023-05-08T12:13:41.312919642Z"}
{"log":"    at \u001b[90mfile:///fgc/\u001b[39mepic-games.js:114:16 {\r\n","stream":"stdout","time":"2023-05-08T12:13:41.312928961Z"}
{"log":"  name: \u001b[32m'TimeoutError'\u001b[39m\r\n","stream":"stdout","time":"2023-05-08T12:13:41.31293839Z"}
{"log":"}\r\n","stream":"stdout","time":"2023-05-08T12:13:41.312947604Z"}
{"log":"Xvfb display server created screen with resolution 1280x1280\r\n","stream":"stdout","time":"2023-05-08T12:13:59.514642678Z"}
{"log":"VNC is running on port 5900 (no password!)\r\n","stream":"stdout","time":"2023-05-08T12:13:59.601270035Z"}
{"log":"noVNC (VNC via browser) is running on http://localhost:6080\r\n","stream":"stdout","time":"2023-05-08T12:13:59.601349086Z"}
{"log":"\r\n","stream":"stdout","time":"2023-05-08T12:13:59.601360578Z"}
{"log":"2023-05-08 12:13:59.959 started checking epic-games\r\n","stream":"stdout","time":"2023-05-08T12:13:59.960778253Z"}
{"log":"Signed in as Someash-Energy\r\n","stream":"stdout","time":"2023-05-08T12:14:05.847858198Z"}
{"log":"Free games: [\r\n","stream":"stdout","time":"2023-05-08T12:14:09.92339677Z"}
{"log":"  \u001b[32m'https://store.epicgames.com/en-US/p/against-all-odds-409105'\u001b[39m,\r\n","stream":"stdout","time":"2023-05-08T12:14:09.923435871Z"}
{"log":"  \u001b[32m'https://store.epicgames.com/en-US/p/horizon-chase-turbo'\u001b[39m,\r\n","stream":"stdout","time":"2023-05-08T12:14:09.923441955Z"}
{"log":"  \u001b[32m'https://store.epicgames.com/en-US/p/kao-the-kangaroo-62abe3'\u001b[39m\r\n","stream":"stdout","time":"2023-05-08T12:14:09.923446752Z"}
{"log":"]\r\n","stream":"stdout","time":"2023-05-08T12:14:09.923451316Z"}
{"log":"page.goto: Timeout 60000ms exceeded.\r\n","stream":"stdout","time":"2023-05-08T12:15:09.925610926Z"}
{"log":"=========================== logs ===========================\r\n","stream":"stdout","time":"2023-05-08T12:15:09.925648673Z"}
{"log":"navigating to \"https://store.epicgames.com/en-US/p/against-all-odds-409105\", waiting until \"load\"\r\n","stream":"stdout","time":"2023-05-08T12:15:09.925654479Z"}
{"log":"============================================================\r\n","stream":"stdout","time":"2023-05-08T12:15:09.925659586Z"}
{"log":"    at \u001b[90mfile:///fgc/\u001b[39mepic-games.js:114:16 {\r\n","stream":"stdout","time":"2023-05-08T12:15:09.925663984Z"}
{"log":"  name: \u001b[32m'TimeoutError'\u001b[39m\r\n","stream":"stdout","time":"2023-05-08T12:15:09.925668745Z"}
{"log":"}\r\n","stream":"stdout","time":"2023-05-08T12:15:09.92567335Z"}
{"log":"Xvfb display server created screen with resolution 1280x1280\r\n","stream":"stdout","time":"2023-05-08T12:27:04.578577997Z"}
{"log":"VNC is running on port 5900 (no password!)\r\n","stream":"stdout","time":"2023-05-08T12:27:04.661487268Z"}
{"log":"noVNC (VNC via browser) is running on http://localhost:6080\r\n","stream":"stdout","time":"2023-05-08T12:27:04.661662686Z"}
{"log":"\r\n","stream":"stdout","time":"2023-05-08T12:27:04.661674017Z"}
{"log":"2023-05-08 12:27:04.995 started checking epic-games\r\n","stream":"stdout","time":"2023-05-08T12:27:04.99656887Z"}
{"log":"Signed in as Someash-Energy\r\n","stream":"stdout","time":"2023-05-08T12:27:09.822754685Z"}
{"log":"Free games: [\r\n","stream":"stdout","time":"2023-05-08T12:27:15.315560604Z"}
{"log":"  \u001b[32m'https://store.epicgames.com/en-US/p/against-all-odds-409105'\u001b[39m,\r\n","stream":"stdout","time":"2023-05-08T12:27:15.315593984Z"}
{"log":"  \u001b[32m'https://store.epicgames.com/en-US/p/horizon-chase-turbo'\u001b[39m,\r\n","stream":"stdout","time":"2023-05-08T12:27:15.315599712Z"}
{"log":"  \u001b[32m'https://store.epicgames.com/en-US/p/kao-the-kangaroo-62abe3'\u001b[39m\r\n","stream":"stdout","time":"2023-05-08T12:27:15.315604967Z"}
{"log":"]\r\n","stream":"stdout","time":"2023-05-08T12:27:15.315609571Z"}
{"log":"Current free game: Against All Odds\r\n","stream":"stdout","time":"2023-05-08T12:28:15.314637238Z"}
{"log":"  Already in library! Nothing to claim.\r\n","stream":"stdout","time":"2023-05-08T12:28:15.314697208Z"}
{"log":"Current free game: Horizon Chase Turbo\r\n","stream":"stdout","time":"2023-05-08T12:28:23.534344585Z"}
{"log":"  Already in library! Nothing to claim.\r\n","stream":"stdout","time":"2023-05-08T12:28:23.534377908Z"}
{"log":"page.goto: Timeout 60000ms exceeded.\r\n","stream":"stdout","time":"2023-05-08T12:29:23.5389067Z"}

**Comment by vogler** [comment] 2023-05-08 15:56
What hardware/network are you using? Seems like it's so slow that it reaches the 60s timeout.
Note that it happened for different URLs:
```
navigating to \"https://store.epicgames.com/en-US/p/against-all-odds-409105
navigating to \"https://store.epicgames.com/en-US/p/kao-the-kangaroo-62abe3
navigating to \"https://store.epicgames.com/en-US/p/against-all-odds-409105
navigating to \"https://store.epicgames.com/en-US/p/kao-the-kangaroo-62abe3
```
You can run it with e.g. `TIMEOUT=180` instead.

**Comment by someash** [comment] 2023-05-08 16:02
![image](https://user-images.githubusercontent.com/32922655/236872733-33ea99c1-7ac8-4cab-b57d-173b6780727d.png)
Is this config.env file formatted correctly?

**Comment by vogler** [comment] 2023-05-10 06:46
Looks like there's some space after the `'`, but maybe it's just your font.
https://github.com/motdotla/dotenv is used for parsing the config.
https://github.com/caronc/apprise is used for notifications.
See https://github.com/caronc/apprise/wiki/Notify_email for how to use it for email.
You can also test `apprise` in the docker image by just appending the command.

---

> What hardware/network are you using?

Did it work with the increased timeout?

**Comment by GothicIII** [comment] 2023-05-11 09:38
I don't use docker for grabbing but using the script route.
I am calling regularly `node /path/epic_games,js` within the users crontab. Output is beeing logged.

It runs but always fails due to a timeout. The strange thing is that is works if I call that line from within a ssh session with the same user.
Sorry I flushed the logs so I have to wait until the new games come up.
It seems that the browser is running because it gets the list of not claimed games. Then it clicks to claim them and then the timeout happens. When the games are claimed already the script does properly exit with 'nothing to claim'.

Has anybody a clue what is going on? Can't say if gog or prime are working because of lack of free offers.

**Comment by vogler** [comment] 2023-05-11 10:06
@GothicIII This seems like a separate issue.

> The strange thing is that is works if I call that line from within a ssh session with the same user.

Then it's probably related to how it's run as a cronjob. Is it running with the same options? Does it load `data/config.env` or do you set variables? If you have some desktop environment, you can try `SHOW=1`.

**Comment by vogler** [comment] 2023-05-18 15:37
@someash I'll close this for now. Let me know if increasing `TIMEOUT` (or running on a faster machine) did not fix the issue.

**Closed by vogler** 2023-05-18 15:37 UTC
Labels: bug, store: epic-games, can't reproduce
