### ISSUE TITLE
The script doesn't claim the games

### ISSUE THREAD

**Issue by CheeseBeese** [vogler/free-games-claimer#111] opened 2023-03-24 19:12 UTC
Like i said in the title, it doesnt work. It finds the games and then says: click GET. and after that it gets some sort of timeout error.

LOG:
```
PS C:\Commands> docker run --rm -it -p 6080:6080 -v fgc:/fgc/data --pull=always ghcr.io/vogler/free-games-claimer node epic-games
latest: Pulling from vogler/free-games-claimer
Digest: sha256:e4a861e4cea33ca852671118ee630c1e68798e066fa4685add94be38ce3a1a45
Status: Image is up to date for ghcr.io/vogler/free-games-claimer:latest
Xvfb display server created screen with resolution 1280x1280
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080

2023-03-24 19:03:22.787 started checking epic-games
Signed in as de-lollige-man
Free games: [
  'https://store.epicgames.com/en-US/p/chess-ultra-91bba3',
  'https://store.epicgames.com/en-US/p/world-of-warships--starter-pack-ishizuchi'
]
Current free game: Chess Ultra
  Not in library yet! Click GET.
locator.click: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for frameLocator('#webPurchaseContainer iframe').locator('button:has-text("Place Order"):not(:has(.payment-loading--loading))')
============================================================
    at file:///fgc/epic-games.js:176:99 {
  name: 'TimeoutError'
}
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ProtocolError: Target closed
    at /fgc/node_modules/playwright-core/lib/server/firefox/ffConnection.js:189:16
    at new Promise (<anonymous>)
    at FFSession.send (/fgc/node_modules/playwright-core/lib/server/firefox/ffConnection.js:185:12)
    at RawMouseImpl.move (/fgc/node_modules/playwright-core/lib/server/firefox/ffInput.js:91:24)
    at Mouse.move (/fgc/node_modules/playwright-core/lib/server/input.js:153:23)
    at Mouse.click (/fgc/node_modules/playwright-core/lib/server/input.js:180:12)
    at /fgc/node_modules/playwright-core/lib/server/dom.js:468:109
    at /fgc/node_modules/playwright-core/lib/server/dom.js:430:13
    at FrameManager.waitForSignalsCreatedBy (/fgc/node_modules/playwright-core/lib/server/frames.js:114:26)
    at ElementHandle._performPointerAction (/fgc/node_modules/playwright-core/lib/server/dom.js:424:57) {
  sessionClosed: true
}
```

**Comment by vogler** [comment] 2023-03-30 14:44
Duplicate of #106.

**Closed** 2023-03-30 14:59 UTC
Labels: bug, store: epic-games, can't reproduce
