### ISSUE TITLE
GOG TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by Kaschtelator** [vogler/free-games-claimer#414] opened 2024-12-22 16:09 UTC
--- Exception:

TypeError: Cannot read properties of null (reading '1')

    at file:///fgc/gog.js:102:62

**Comment by sudoShiba** [comment] 2024-12-29 00:26
i have the same error

**Comment by sudoShiba** [comment] 2024-12-29 00:27
i see there is already a pull request on this though
https://github.com/vogler/free-games-claimer/pull/411

**Comment by vogler** [comment] 2024-12-30 03:25
Duplicate of #398.

**Closed by vogler** 2024-12-30 03:25 UTC
