### ISSUE TITLE
Discord Notification Failed for Prime Gaming DLC (PG_CLAIMDLC)

### ISSUE THREAD

**Issue by Targunitoth** [vogler/free-games-claimer#144] opened 2023-05-19 07:44 UTC
Hello, I don't get notifications for Prime Games, instead I get the following error message:
```
...
fgc                   | Number of unclaimed DLC: 3
fgc                   | locator.getAttribute: Error: strict mode violation: locator('div[data-a-target="offer-list-IN_GAME_LOOT"] [data-a-target="item-card"]:has(p:text-is("Claim"))').first().locator('a') resolved to 2 elements:
fgc                   |     1) <a data-a-target="learn-more-card" data-a-selector=…>…</a> aka getByRole('link', { name: 'Go to D.Va Waveracer Legendary Skin offer' })
fgc                   |     2) <a class="tw-interactive tw-button" href="/dva-wave…>…</a> aka getByRole('link', { name: 'Go to D.Va Waveracer Legendary Skin offer' }).getByRole('link', { name: 'Claim' })
fgc                   |
fgc                   | =========================== logs ===========================
fgc                   | waiting for locator('div[data-a-target="offer-list-IN_GAME_LOOT"] [data-a-target="item-card"]:has(p:text-is("Claim"))').first().locator('a')
fgc                   | ============================================================
fgc                   |     at file:///fgc/prime-gaming.js:253:66
fgc                   |     at async file:///fgc/prime-gaming.js:250:18
fgc                   | error: Command failed: apprise 'discord:///*********/*****************************' -i html '' -b 'prime-gaming failed: locator.getAttribute: Error: strict mode violation: locator('div[data-a-target="offer-list-IN_GAME_LOOT"] [data-a-target="item-card"]:has(p:text-is("Claim"))').first().locator('a') resolved to 2 elements:'
fgc                   | /bin/sh: 1: Syntax error: "(" unexpected
...
```

also for other games:
```
fgc                   | locator.getAttribute: Error: strict mode violation: locator('div[data-a-target="offer-list-IN_GAME_LOOT"] [data-a-target="item-card"]:has(p:text-is("Claim"))').first().locator('a') resolved to 2 elements:
fgc                   |     1) <a data-a-target="learn-more-card" data-a-selector=…>…</a> aka getByRole('link', { name: 'Go to Hit the Bag Exotic Emote Bundle offer' })
fgc                   |     2) <a class="tw-interactive tw-button" href="/hit-the-…>…</a> aka getByRole('link', { name: 'Claim' })
```

**Comment by vogler** [comment] 2023-05-19 07:57
Duplicate of #142, should have been fixed by https://github.com/vogler/free-games-claimer/commit/290fe289d4dac79e595f5bddf9ed54a72dd75a2a. Did you update your image?

**Closed by vogler** 2023-05-19 07:57 UTC
